site_name: RIDDLE&CODE
theme:
  name: 'rtd-dropdown'
  
nav:
- Digital Asset Management: 
  - Introduction: 'index.md'
  - Product Description: 'ProductDescription.md'
  - Architecture Overview: 'Architecture-Overview.md'
  - Initial Set Up: 'SetUp.md'
  - Signing: 'Signing.md'
  - Manual: 'Manual.md'
  - Operations: 'Operations.md'
  - Security: 'Security.md'
  - Reconciliation: 'Reconciliation.md'
  - Fee Addon: 'Fee-estimates.md'
  - Key Ceremony: 'KeyCeremony.md'
  -   Key Ceremony 2 parties: 'KeyCeremony-2parties.md'
  -   Key Ceremony 3 parties: 'KeyCeremony-3parties-user-case.md'
  - Backup: 'Backup.md'
  - Glossary: 'Glossary.md'
  
plugins:
  - search
