site_name: RIDDLE&CODE

theme:
  name: 'rtd-dropdown'

nav:
- Home: index.md
- Token Management Platform:
        - Product Documentation: Product-Documentation.md
        - Manuals: Token_Management_Platform_Manual.md
        - Use Cases: Use-Cases.md
        - Frequently asked questions: FAQ.md

- Glossary: 
        - What's What: Glossary.md
        
extra_css:
  - design/extra_css
  
plugins:
  - search