site_name: RIDDLE&CODE
theme:
  name: 'rtd-dropdown'
  
nav:
- Digital Asset Custody: 
  - Introduction: 'index.md'
  - Product Description: 'ProductDescription.md'
  - Architecture Overview: 'Architecture-Overview.md'
  - Installation guide: 'Installation-Guide.md'
  - Amin menu operations: 'Admin-menu-operations.md'
  - Key management: 'Key-management.md'
  - Key ceremonies: 'Key-ceremonies.md'
  - Signing: 'Signing-of-transactions.md'
  - Glossary: 'Glossary.md'  
plugins:
  - search 