site_name: RIDDLE&CODE

theme:
  name: 'rtd-dropdown'

nav:
- Home: index.md
- Token Management Platform:
        - Product Introduction: Product-Description.md

- Manuals:
        - User Manuals: Token_Management_Platform_Manual.md

- Glossary: 
        - What's What: Glossary.md
- FAQ:
        - FAQ: FAQ.md

extra_css:
  - design/extra_css
  
plugins:
  - search