site_name: RIDDLE&CODE
theme:
  name: 'rtd-dropdown'
  
nav:
- Token Management Platform: 
 - Introduction: 'index.md'
 - Architecture Overview: 'Architecture-Overview.md'
 - Transaction Approval: 'transction-approval.md'
 - Policy Layer: 'Policy-Layer.md'
 - Approval Device: 'approval-device.md'
 - Key Managemeent: 'Key-management.md'
 - Audit Trail: 'audit-trail.md'
 - Reconciliation: 'reconciliation.md'
 - AML: 'aml.md'
 - APIs: 'apis.md'
 - Full Node Service: 'full-node-service.md'
 - Key ceremony: 'key-ceremony.md'
 - Interfacea: 'user-interface.md'
 - GDPR: 'gdpr.md'
 - Glossary: 'Glossary.md'

plugins:
  - search