site_name: RIDDLE&CODE

theme:
  name: 'rtd-dropdown'
  highlightjs: true
  features:
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.tabs
nav:
- Home: index.md
- Token Management Platform:
        - Product Documentation: Product-Documentation.md
        - Manuals: Token_Management_Platform_Manual.md
        - Use Cases: Use-Cases.md
        - Frequently asked questions: FAQ.md
        - Release Notes: release-notes-tmp.md

- Glossary: 
        - What's What: Glossary.md
        
#extra_css:
#  - design/extra_css
  
plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3