site_name: RIDDLE&CODE

theme:
  name: 'rtd-dropdown'
  highlightjs: true
  features:
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.tabs
nav:
- Home: index.md
- Token Management Platform:
        - Product Documentation: Product-Documentation.md
        - Getting started guide for Administrators: getting-started-administrators.md
        - Getting started guide for Traders: getting-started-trader.md
        - Key Ceremony: Key-ceremony.md
          - Shamir-based Key generation: Shamir-based-key-generation.md
        - Use Cases: Use-Cases.md
        - Frequently Asked Questions: FAQ.md
        - Release Notes: release-notes-tmp.md
        - Glossary: Glossary.md
- Confidential Key Management:
        - Product Documentation: CKM-Product-Documentation.md
        - Getting Started Guide: CKM_Getting_Started_Guide.md
        - Key Ceremony: CKM-Key-ceremony.md

        
#extra_css:
#  - design/extra_css
  
plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - fontawesome_markdown