site_name: RIDDLE&CODE

theme:
  name: 'rtd-dropdown'

nav:
- Home: index.md
- Token Management Platform:
        - Documentation: Product-Documentation.md
        - Use Cases: Use-Cases.md

- Manuals:
        - All Users: Token_Management_Platform_Manual.md

- Glossary: 
        - What's What: Glossary.md
        
- FAQ:
        - Frequently asked questions: FAQ.md

extra_css:
  - design/extra_css
  
plugins:
  - search