site_name: RIDDLE&CODE
theme:
  name: 'rtd-dropdown'
  
nav:
- Digital Asset Custody: 
  - Introduction: 'index.md'
  - Architecture Overview: 'Architecture-Overview.md'
  - Transaction Approval: 'transaction-approval.md'
  - Policy Layer: 'Policy-Layer.md'
  - Approval Device: 'approval-device.md'
  - Key Management: 'Key-management.md'
  - Key ceremony: 'key-ceremony.md'
  - Audit Trail: 'audit-trail.md'
  - Reconciliation: 'reconciliation.md'
  - AML: 'AML.md'
  - APIs: 'apis.md'
  - Full Node Service: 'full-node-service.md'
  - Interfacea: 'user-interface.md'
  - GDPR: 'gdpr.md'
  - Glossary: 'Glossary.md'
plugins:
  - search
