site_name: RIDDLE&CODE
theme:
  name: 'rtd-dropdown'
  
nav:
- Home: 'index.md'
- Product Introduction:
  - Architecture Overview: 'Architecture-Overview.md'
  - Design philosophy: 'design-philosophy.md'
  - Transaction Approval: 'transaction-approval.md'
  - Policy Layer: 'Policy-Layer.md'
  - Approval Device: 'approval-device.md'
  - Key Management: 'Key-management.md'
  - Key ceremony: 'key-ceremony.md'
  - Audit Trail: 'audit-trail.md'
  - Reconciliation: 'Reconciliation.md'
  - AML: 'AML.md'
  - APIs: 'apis.md'
  - Full Node Service: 'full-node-service.md'
  - Interfaces: 'user-interface.md'
  - GDPR: 'gdpr.md'
- User Manuals: 'Token_Management_Platform_Manual.md'
- Glossary: 'Glossary.md'
- FAQ: 'FAQ.md'
plugins:
  - search