site_name: RIDDLE&CODE Digital Asset Management
theme:
  name: 'rtd-dropdown'
nav:
  - Introduction: 'index.md'
  - Product Description: 'ProductDescription.md'
  - Initial Set Up: 'SetUp.md'
  - Signing: 'Signing.md'
  - Manual: 'Manual.md'
  - Operations: 'Operations.md'
  - Security: 'Security.md'
  - Key Ceremony: 'KeyCeremony.md'
  - Key Ceremony 2 persons: 'KeyCeremony-2persons.md'
  - Key Ceremony 3 persons: 'KeyCeremony-3persons-user-case.md'
  - Backup: 'Backup.md'
  - Glossary: 'Glossary.md'
  

plugins:
  - search
